#ifndef _EPS_DEVICE_CFG_H_
#define _EPS_DEVICE_CFG_H_

/*
** Eps Device Configuration
** This file is auto-generated by the tryspace-orchestrator.py script.
*/
#ifndef EPS_CFG
#define EPS_CFG_STRING      "/dev/usart_5"
#define EPS_CFG_HANDLE      5
#define EPS_CFG_BAUDRATE_HZ 115200
#define EPS_CFG_MS_TIMEOUT  250
#define EPS_CFG_DEBUG
#endif

#endif /* _EPS_DEVICE_CFG_H_ */